### ISSUE TITLE
Add Featured Image

### ISSUE THREAD

**Issue by TwisterMc** [Krielkip/bb-toolbox#2]
I added the ability to add featured images and it's working, but I feel like it's not using the same format as you were. Plus, the module doesn't remember the image I selected so it's not ideal. Not sure what's going on. Maybe you can adapt it.

```
'post_featuredImage'     => array(
    'type'          => 'photo',
    'label'         => __('Featured Image', 'bb-toolbox'),
 ),
```

In the `save_toolbox_settings` function I added:
```
$featuredImage = $settings['post_featuredImage'];
set_post_thumbnail( $post_id, $featuredImage );
```

**Comment by Krielkip** [comment]
Good idea to add the featuredimage to this box.
Thanks already for some pre work. i will try to work it in this week :)

**Comment by Krielkip** [comment]
An update. I have worked on the script: 
- Adding, updating a new thumbnail is working, also settings that show the thumbs works
- Fixed a bug of refreshing the page. Something with post_parent en my own bad logic.

ToDo:
- Remove the image 
- Edit button to show
- Update view when changed the image.

**Comment by Krielkip** [comment]
New list of ToDo:
- Update view when changed the image.
